-- シフカレ Live データベース設定
-- Supabase Dashboard > SQL Editor で全文を1回実行してください。

create extension if not exists pgcrypto;

-- 既に作成済みの members テーブルを安全に補完します。
create table if not exists public.members (
  id uuid primary key default gen_random_uuid(),
  email text unique not null,
  name text not null,
  is_host boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.members add column if not exists is_host boolean not null default false;
alter table public.members add column if not exists created_at timestamptz not null default now();
create unique index if not exists members_email_lower_key on public.members (lower(email));

insert into public.members (email, name, is_host)
values ('kowita51@gmail.com', '多田 昂太', true)
on conflict (email) do update set is_host = true;

create table if not exists public.shifts (
  id uuid primary key default gen_random_uuid(),
  member_id uuid not null references public.members(id) on delete cascade,
  shift_date date not null,
  start_time time not null,
  end_time time not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shifts_time_order check (end_time > start_time),
  constraint shifts_member_date_time_unique unique (member_id, shift_date, start_time, end_time)
);

create index if not exists shifts_date_idx on public.shifts (shift_date);
create index if not exists shifts_member_idx on public.shifts (member_id);

create table if not exists public.shift_history (
  id bigint generated by default as identity primary key,
  action text not null check (action in ('insert','update','delete')),
  actor_email text,
  member_id uuid,
  member_name text,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

-- RLSポリシー内から安全に会員状態を確認する関数です。
create or replace function public.is_registered_member()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.members
    where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

create or replace function public.is_host_member()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.members
    where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
      and is_host = true
  );
$$;

revoke all on function public.is_registered_member() from public;
revoke all on function public.is_host_member() from public;
grant execute on function public.is_registered_member() to authenticated;
grant execute on function public.is_host_member() to authenticated;

alter table public.members enable row level security;
alter table public.shifts enable row level security;
alter table public.shift_history enable row level security;

drop policy if exists "members_read_registered" on public.members;
create policy "members_read_registered" on public.members
for select to authenticated using (public.is_registered_member());

drop policy if exists "members_insert_host" on public.members;
create policy "members_insert_host" on public.members
for insert to authenticated with check (public.is_host_member());

drop policy if exists "members_update_host" on public.members;
create policy "members_update_host" on public.members
for update to authenticated using (public.is_host_member()) with check (public.is_host_member());

drop policy if exists "members_delete_host" on public.members;
create policy "members_delete_host" on public.members
for delete to authenticated using (public.is_host_member() and lower(email) <> lower(auth.jwt() ->> 'email'));

drop policy if exists "shifts_read_registered" on public.shifts;
create policy "shifts_read_registered" on public.shifts
for select to authenticated using (public.is_registered_member());

drop policy if exists "shifts_insert_registered" on public.shifts;
create policy "shifts_insert_registered" on public.shifts
for insert to authenticated with check (public.is_registered_member());

drop policy if exists "shifts_update_registered" on public.shifts;
create policy "shifts_update_registered" on public.shifts
for update to authenticated using (public.is_registered_member()) with check (public.is_registered_member());

drop policy if exists "shifts_delete_registered" on public.shifts;
create policy "shifts_delete_registered" on public.shifts
for delete to authenticated using (public.is_registered_member());

drop policy if exists "history_read_registered" on public.shift_history;
create policy "history_read_registered" on public.shift_history
for select to authenticated using (public.is_registered_member());

-- シフトの追加・変更・削除履歴を自動保存します。
create or replace function public.record_shift_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_id uuid;
  target_name text;
begin
  target_id := coalesce(new.member_id, old.member_id);
  select name into target_name from public.members where id = target_id;
  insert into public.shift_history(action, actor_email, member_id, member_name, old_data, new_data)
  values (
    lower(tg_op),
    lower(coalesce(auth.jwt() ->> 'email', 'unknown')),
    target_id,
    target_name,
    case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) else null end
  );
  return coalesce(new, old);
end;
$$;

drop trigger if exists shifts_history_trigger on public.shifts;
create trigger shifts_history_trigger
after insert or update or delete on public.shifts
for each row execute function public.record_shift_history();

grant select on public.members, public.shifts, public.shift_history to authenticated;
grant insert, update, delete on public.shifts to authenticated;
grant insert, update, delete on public.members to authenticated;

-- Realtime対象へ追加（既に追加済みでもエラーにならないようにします）。
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'shifts'
  ) then alter publication supabase_realtime add table public.shifts; end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'members'
  ) then alter publication supabase_realtime add table public.members; end if;
end $$;
