-- テスト版専用データ領域
-- 本番の members / shifts / shift_history / closed_days は変更しません。
-- 初回実行時だけ、本番データをテスト領域へコピーします。

create table if not exists public.test_members (
  id uuid primary key references public.members(id) on delete cascade,
  name text not null,
  display_name text,
  is_host boolean not null default false
);

create table if not exists public.test_shifts (
  id uuid primary key default gen_random_uuid(),
  member_id uuid not null references public.test_members(id) on delete cascade,
  shift_date date not null,
  start_time time not null,
  end_time time not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_time > start_time)
);

create table if not exists public.test_shift_history (
  id bigint generated by default as identity primary key,
  action text not null check (action in ('insert','update','delete')),
  actor_member_id uuid references public.members(id) on delete set null,
  member_id uuid references public.members(id) on delete set null,
  member_name text,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.test_closed_days (
  closed_date date primary key,
  label text not null,
  kind text not null default 'temporary' check (kind in ('holiday','temporary')),
  created_by uuid references public.members(id) on delete set null,
  created_at timestamptz not null default now()
);

-- テスト領域が空のときだけ現在の本番データを初期値としてコピー
insert into public.test_members(id,name,display_name,is_host)
select id,name,display_name,is_host from public.members
on conflict(id) do nothing;

insert into public.test_shifts(id,member_id,shift_date,start_time,end_time,created_at,updated_at)
select id,member_id,shift_date,start_time,end_time,created_at,updated_at from public.shifts
where not exists(select 1 from public.test_shifts);

insert into public.test_closed_days(closed_date,label,kind,created_by,created_at)
select closed_date,label,kind,created_by,created_at from public.closed_days
where not exists(select 1 from public.test_closed_days);

alter table public.test_members enable row level security;
alter table public.test_shifts enable row level security;
alter table public.test_shift_history enable row level security;
alter table public.test_closed_days enable row level security;

drop policy if exists test_members_read on public.test_members;
drop policy if exists test_shifts_read on public.test_shifts;
drop policy if exists test_history_read on public.test_shift_history;
drop policy if exists test_closed_days_read on public.test_closed_days;
create policy test_members_read on public.test_members for select to authenticated using(public.is_registered_user());
create policy test_shifts_read on public.test_shifts for select to authenticated using(public.is_registered_user());
create policy test_history_read on public.test_shift_history for select to authenticated using(public.is_registered_user());
create policy test_closed_days_read on public.test_closed_days for select to authenticated using(public.is_registered_user());

revoke insert,update,delete on public.test_members,public.test_shifts,public.test_shift_history,public.test_closed_days from authenticated;
grant select on public.test_members,public.test_shifts,public.test_shift_history,public.test_closed_days to authenticated;

create or replace function public.test_set_display_name(p_member_id uuid,p_display_name text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.valid_member(p_member_id) then raise exception 'メンバーを確認できません'; end if;
  if char_length(btrim(p_display_name)) not between 1 and 24 then raise exception '表示名は1〜24文字で入力してください'; end if;
  update public.test_members set display_name=btrim(p_display_name) where id=p_member_id;
end $$;

create or replace function public.test_create_shift(p_actor_member_id uuid,p_target_member_id uuid,p_shift_date date,p_start_time time,p_end_time time)
returns uuid language plpgsql security definer set search_path=public as $$
declare v public.test_shifts; v_name text;
begin
  if not public.valid_member(p_actor_member_id) or not exists(select 1 from public.test_members where id=p_target_member_id) then raise exception 'メンバーを確認できません'; end if;
  if p_end_time<=p_start_time then raise exception '終了時間は開始時間より後にしてください'; end if;
  insert into public.test_shifts(member_id,shift_date,start_time,end_time) values(p_target_member_id,p_shift_date,p_start_time,p_end_time) returning * into v;
  select name into v_name from public.test_members where id=p_target_member_id;
  insert into public.test_shift_history(action,actor_member_id,member_id,member_name,new_data) values('insert',p_actor_member_id,p_target_member_id,v_name,to_jsonb(v));
  return v.id;
end $$;

create or replace function public.test_update_shift(p_shift_id uuid,p_actor_member_id uuid,p_target_member_id uuid,p_shift_date date,p_start_time time,p_end_time time)
returns void language plpgsql security definer set search_path=public as $$
declare old_v public.test_shifts; new_v public.test_shifts; v_name text;
begin
  if not public.valid_member(p_actor_member_id) or not exists(select 1 from public.test_members where id=p_target_member_id) then raise exception 'メンバーを確認できません'; end if;
  select * into old_v from public.test_shifts where id=p_shift_id; if old_v.id is null then raise exception 'シフトが見つかりません'; end if;
  if p_end_time<=p_start_time then raise exception '終了時間は開始時間より後にしてください'; end if;
  update public.test_shifts set member_id=p_target_member_id,shift_date=p_shift_date,start_time=p_start_time,end_time=p_end_time,updated_at=now() where id=p_shift_id returning * into new_v;
  select name into v_name from public.test_members where id=p_target_member_id;
  insert into public.test_shift_history(action,actor_member_id,member_id,member_name,old_data,new_data) values('update',p_actor_member_id,p_target_member_id,v_name,to_jsonb(old_v),to_jsonb(new_v));
end $$;

create or replace function public.test_delete_shift(p_shift_id uuid,p_actor_member_id uuid)
returns void language plpgsql security definer set search_path=public as $$
declare old_v public.test_shifts; v_name text;
begin
  if not public.valid_member(p_actor_member_id) then raise exception 'メンバーを確認できません'; end if;
  delete from public.test_shifts where id=p_shift_id returning * into old_v; if old_v.id is null then raise exception 'シフトが見つかりません'; end if;
  select name into v_name from public.test_members where id=old_v.member_id;
  insert into public.test_shift_history(action,actor_member_id,member_id,member_name,old_data) values('delete',p_actor_member_id,old_v.member_id,v_name,to_jsonb(old_v));
end $$;

create or replace function public.test_bulk_replace_shifts(p_actor_member_id uuid,p_target_member_id uuid,p_rows jsonb,p_replace boolean default true)
returns integer language plpgsql security definer set search_path=public as $$
declare r jsonb; old_v public.test_shifts; new_v public.test_shifts; v_name text; n int:=0;
begin
  if not public.valid_member(p_actor_member_id) or not exists(select 1 from public.test_members where id=p_target_member_id) then raise exception 'メンバーを確認できません'; end if;
  select name into v_name from public.test_members where id=p_target_member_id;
  if p_replace then
    for old_v in delete from public.test_shifts where member_id=p_target_member_id and shift_date in (select (x->>'shift_date')::date from jsonb_array_elements(p_rows) x) returning * loop
      insert into public.test_shift_history(action,actor_member_id,member_id,member_name,old_data) values('delete',p_actor_member_id,p_target_member_id,v_name,to_jsonb(old_v));
    end loop;
  end if;
  for r in select * from jsonb_array_elements(p_rows) loop
    insert into public.test_shifts(member_id,shift_date,start_time,end_time) values(p_target_member_id,(r->>'shift_date')::date,(r->>'start_time')::time,(r->>'end_time')::time) returning * into new_v;
    insert into public.test_shift_history(action,actor_member_id,member_id,member_name,new_data) values('insert',p_actor_member_id,p_target_member_id,v_name,to_jsonb(new_v)); n:=n+1;
  end loop;
  return n;
end $$;

create or replace function public.test_set_closed_day(p_actor_member_id uuid,p_closed_date date,p_label text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.valid_member(p_actor_member_id) then raise exception 'メンバーを確認できません'; end if;
  if exists(select 1 from public.test_closed_days where closed_date=p_closed_date and kind='holiday') then raise exception '祝日は変更できません'; end if;
  insert into public.test_closed_days(closed_date,label,kind,created_by) values(p_closed_date,btrim(p_label),'temporary',p_actor_member_id)
  on conflict(closed_date) do update set label=excluded.label,created_by=excluded.created_by;
end $$;

create or replace function public.test_delete_closed_day(p_actor_member_id uuid,p_closed_date date)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.valid_member(p_actor_member_id) then raise exception 'メンバーを確認できません'; end if;
  delete from public.test_closed_days where closed_date=p_closed_date and kind='temporary';
end $$;

grant execute on function public.test_set_display_name(uuid,text) to authenticated;
grant execute on function public.test_create_shift(uuid,uuid,date,time,time) to authenticated;
grant execute on function public.test_update_shift(uuid,uuid,uuid,date,time,time) to authenticated;
grant execute on function public.test_delete_shift(uuid,uuid) to authenticated;
grant execute on function public.test_bulk_replace_shifts(uuid,uuid,jsonb,boolean) to authenticated;
grant execute on function public.test_set_closed_day(uuid,date,text) to authenticated;
grant execute on function public.test_delete_closed_day(uuid,date) to authenticated;

do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='test_shifts') then alter publication supabase_realtime add table public.test_shifts; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='test_members') then alter publication supabase_realtime add table public.test_members; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='test_closed_days') then alter publication supabase_realtime add table public.test_closed_days; end if;
end $$;
