import {useEffect,useMemo,useState} from 'react';
import {CalendarDays,ChevronLeft,ChevronRight,Clock3,History as HistoryIcon,Home,Settings,Users,UtensilsCrossed,Moon,AlertTriangle,X,Plus,Pencil,Trash2,Upload,CalendarOff,LogOut,HeartHandshake,Calculator} from 'lucide-react';
import {ClosedDay,configured,History,includesKind,localDate,Member,parseShiftBoard,serviceRange,Shift,shownName,supabase} from './lib';
import Login from './Login';
import Preferences from './Preferences';
import PayrollSettings from './PayrollSettings';
import './auth.css';
import './preferences.css';

type Tab='today'|'calendar'|'preferences'|'members'|'settings';
type Draft={id?:string;member_id:string;shift_date:string;start_time:string;end_time:string};
const MEMBER_KEY='shiftcal-member-id'; const EDIT_KEY='shiftcal-edit-mode';
const jaDate=(s:string,detail=false)=>new Intl.DateTimeFormat('ja-JP',detail?{month:'long',day:'numeric',weekday:'short'}:{month:'numeric',day:'numeric',weekday:'short'}).format(new Date(`${s}T12:00:00`));

export default function App(){
 const [members,setMembers]=useState<Member[]>([]),[shifts,setShifts]=useState<Shift[]>([]),[auditHistory,setHistory]=useState<History[]>([]),[closedDays,setClosedDays]=useState<ClosedDay[]>([]);
 const [meId,setMeId]=useState(localStorage.getItem(MEMBER_KEY)||''),[tab,setTab]=useState<Tab>('today'),[loading,setLoading]=useState(true),[signedIn,setSignedIn]=useState(false),[error,setError]=useState('');
 const [edit,setEdit]=useState(sessionStorage.getItem(EDIT_KEY)==='1'),[month,setMonth]=useState(()=>new Date()),[selectedDate,setSelectedDate]=useState<string|null>(null),[selectedMember,setSelectedMember]=useState<string|null>(null),[draft,setDraft]=useState<Draft|null>(null),[bulk,setBulk]=useState(false),[payrollOpen,setPayrollOpen]=useState(false);
 const me=members.find(m=>m.id===meId);
 const load=async()=>{const [m,s,h,c]=await Promise.all([supabase.from('members').select('id,name,display_name,is_host').order('name'),supabase.from('shifts').select('*').order('shift_date').order('start_time'),supabase.from('shift_history').select('*').order('created_at',{ascending:false}).limit(50),supabase.from('closed_days').select('closed_date,label,kind').order('closed_date')]);if(m.error||s.error||c.error){setError(m.error?.message||s.error?.message||c.error?.message||'読込に失敗しました');return}setMembers(m.data||[]);setShifts(s.data||[]);setHistory(h.data||[]);setClosedDays((c.data||[]) as ClosedDay[])};
 useEffect(()=>{let active=true;const start=async()=>{if(!configured){setError('Vercelの環境変数が設定されていません');setLoading(false);return}const {data}=await supabase.auth.getSession();const session=data.session;if(!session||session.user.is_anonymous){if(session)await supabase.auth.signOut();if(active){setSignedIn(false);setLoading(false)}return}let mine=await supabase.rpc('current_member_profile').maybeSingle();let mineData=mine.data as Member|null;if(!mineData){try{const params=new URLSearchParams(location.search);const memberId=params.get('register_member');const code=params.get('register_code');const pending=memberId&&code?{memberId,code}:JSON.parse(localStorage.getItem('shiftcal-pending-registration')||'null') as {memberId:string;code:string}|null;if(pending){const claimed=await supabase.rpc('claim_member',{p_member_id:pending.memberId,p_code:pending.code});if(!claimed.error){localStorage.removeItem('shiftcal-pending-registration');history.replaceState({},'',location.pathname);mine=await supabase.rpc('current_member_profile').maybeSingle();mineData=mine.data as Member|null}}}catch{localStorage.removeItem('shiftcal-pending-registration')}}if(mine.error||!mineData){await supabase.auth.signOut();if(active){setSignedIn(false);setError('登録を完了できませんでした。店舗コードと選択した名前を確認してください。');setLoading(false)}return}if(!active)return;choose(mineData.id);setSignedIn(true);await load();if(active)setLoading(false)};void start();const {data:listener}=supabase.auth.onAuthStateChange(event=>{if(event==='SIGNED_IN')setTimeout(()=>void start(),0);if(event==='SIGNED_OUT'&&active){setSignedIn(false);setLoading(false)}});return()=>{active=false;listener.subscription.unsubscribe()}},[]);
 useEffect(()=>{if(loading||!signedIn)return;const channel=supabase.channel('shiftcal-live').on('postgres_changes',{event:'*',schema:'public',table:'shifts'},load).on('postgres_changes',{event:'*',schema:'public',table:'members'},load).on('postgres_changes',{event:'*',schema:'public',table:'closed_days'},load).subscribe();return()=>{void supabase.removeChannel(channel)}},[loading,signedIn]);
 useEffect(()=>{if(!signedIn)return;void supabase.rpc('current_member_profile').maybeSingle().then(({data})=>{const member=data as Member|null;if(member&&member.id!==meId){localStorage.setItem(MEMBER_KEY,member.id);setMeId(member.id)}})},[signedIn,meId]);
 const choose=(id:string)=>{localStorage.setItem(MEMBER_KEY,id);setMeId(id)};
 const toggleEdit=()=>{const next=!edit;next?sessionStorage.setItem(EDIT_KEY,'1'):sessionStorage.removeItem(EDIT_KEY);setEdit(next)};
 const call=async(fn:string,args:Record<string,unknown>)=>{setError('');const r=await supabase.rpc(fn,args);if(r.error){setError(r.error.message);return false}await load();return true};
 const saveDraft=async(d:Draft)=>{if(!me)return;const args={p_actor_member_id:me.id,p_target_member_id:d.member_id,p_shift_date:d.shift_date,p_start_time:d.start_time,p_end_time:d.end_time};const ok=d.id?await call('update_shift',{p_shift_id:d.id,...args}):await call('create_shift',args);if(ok)setDraft(null)};
 const remove=async(id:string)=>{if(me&&confirm('このシフトを削除しますか？')&&await call('delete_shift',{p_shift_id:id,p_actor_member_id:me.id}))setDraft(null)};
 if(loading)return <div className="splash"><span className="logo">S</span><p>シフトを読み込んでいます</p></div>;
 if(!signedIn)return <Login error={error}/>;
 if(!me)return <div className="splash"><span className="logo">S</span><p>登録情報を確認しています</p></div>;
 const title=tab==='today'?'今日':tab==='calendar'?'カレンダー':tab==='preferences'?'希望シフト':tab==='members'?'メンバー':'設定';
 return <div className="app"><header><div><small>{new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'long'}).format(new Date())}</small><h1>{title}</h1></div><button className={`mode ${edit?'active':''}`} onClick={toggleEdit}>{edit?'変更モード中':'閲覧モード'}</button></header>
  {error&&<div className="error">{error}<button onClick={()=>setError('')}><X size={16}/></button></div>}
  <main>
   {tab==='today'&&<Today shifts={shifts} members={members} me={me} edit={edit} onEdit={setDraft} closed={closedDays.find(c=>c.closed_date===localDate())}/>}
   {tab==='calendar'&&<CalendarView month={month} setMonth={setMonth} shifts={shifts} closedDays={closedDays} onDay={setSelectedDate}/>}
   {tab==='preferences'&&<Preferences member={me} members={members} shifts={shifts}/>}
   {tab==='members'&&<MembersView members={members} shifts={shifts} onMember={setSelectedMember}/>}
   {tab==='settings'&&<SettingsView me={me} members={members} history={auditHistory} edit={edit} onToggle={toggleEdit} onPayroll={()=>setPayrollOpen(true)} onLogout={async()=>{sessionStorage.removeItem(EDIT_KEY);localStorage.removeItem(MEMBER_KEY);setEdit(false);setMeId('');await supabase.auth.signOut()}} onRename={async name=>{if(await call('set_display_name',{p_member_id:me.id,p_display_name:name}))return true;return false}}/>}
  </main>
  {edit&&<button className="fab" onClick={()=>setBulk(true)} aria-label="シフトを登録"><Plus/></button>}
  <nav>{([{id:'today',icon:Home,label:'今日'},{id:'calendar',icon:CalendarDays,label:'カレンダー'},{id:'preferences',icon:HeartHandshake,label:'希望'},{id:'members',icon:Users,label:'メンバー'},{id:'settings',icon:Settings,label:'設定'}] as const).map(i=><button className={tab===i.id?'active':''} onClick={()=>setTab(i.id)} key={i.id}><i.icon/><span>{i.label}</span></button>)}</nav>
  {selectedDate&&<DayModal date={selectedDate} shifts={shifts.filter(s=>s.shift_date===selectedDate)} members={members} edit={edit} closed={closedDays.find(c=>c.closed_date===selectedDate)} onClose={()=>setSelectedDate(null)} onEdit={setDraft} onCloseDay={async(label)=>{if(!me)return;const ok=await call('set_closed_day',{p_actor_member_id:me.id,p_closed_date:selectedDate,p_label:label});if(ok)setSelectedDate(null)}} onOpenDay={async()=>{if(!me)return;const ok=await call('delete_closed_day',{p_actor_member_id:me.id,p_closed_date:selectedDate});if(ok)setSelectedDate(null)}}/>}
  {selectedMember&&<MemberModal member={members.find(m=>m.id===selectedMember)!} shifts={shifts.filter(s=>s.member_id===selectedMember)} onClose={()=>setSelectedMember(null)}/>}
  {draft&&<ShiftModal draft={draft} members={members} onClose={()=>setDraft(null)} onSave={saveDraft} onDelete={remove}/>}
  {bulk&&<BulkModal members={members} me={me} onClose={()=>setBulk(false)} onSave={async(rows,replace)=>{const ok=await call('bulk_replace_shifts',{p_actor_member_id:me.id,p_target_member_id:rows[0].member_id,p_rows:rows.map(r=>({shift_date:r.shift_date,start_time:r.start_time,end_time:r.end_time})),p_replace:replace});if(ok)setBulk(false)}}/>}
  {payrollOpen&&<PayrollSettings member={me} shifts={shifts} onClose={()=>setPayrollOpen(false)}/>}
 </div>
}

function Identity({members,error,onChoose}:{members:Member[];error:string;onChoose:(id:string)=>void}){return <div className="identity"><div className="identity-card"><span className="logo">S</span><p className="eyebrow">シフト共有カレンダー</p><h1>あなたは誰ですか？</h1><p>最初の一度だけ選んでください。この端末に記憶します。</p>{error&&<div className="error">{error}</div>}<div className="people">{members.map((m,i)=><button key={m.id} onClick={()=>onChoose(m.id)}><span>{shownName(m).slice(0,1)}</span><b>{shownName(m)}</b><small>{i%2?'DINNER CREW':'TEAM MEMBER'}</small></button>)}</div></div></div>}
function ShiftList({type,shifts,members,edit,onEdit}:{type:'lunch'|'dinner';shifts:Shift[];members:Member[];edit:boolean;onEdit:(d:Draft)=>void}){const rows=shifts.map(shift=>({shift,range:serviceRange(shift,type)})).filter((row):row is {shift:Shift;range:{start:string;end:string}}=>row.range!==null).sort((a,b)=>a.range.start.localeCompare(b.range.start));return <section className={`service ${type}`}><div className="service-head"><div>{type==='lunch'?<UtensilsCrossed/>:<Moon/>}<div><small>{type==='lunch'?'LUNCH':'DINNER'}</small><h2>{type==='lunch'?'ランチ':'ディナー'}</h2></div></div><div className={`count ${rows.length<=2?'warn':''}`}>{rows.length<=2&&<AlertTriangle/>}<strong>{rows.length}</strong><span>人</span></div></div><div className="shift-list">{rows.length?rows.map(({shift:s,range})=><button key={s.id} onClick={()=>edit&&onEdit(s)}><time>{range.start}</time><span className="avatar">{shownName(members.find(m=>m.id===s.member_id)).slice(0,1)}</span><b>{shownName(members.find(m=>m.id===s.member_id))}</b><small>{range.end}まで</small>{edit&&<Pencil size={16}/>}</button>):<div className="empty">登録されたシフトはありません</div>}</div></section>}
function Today(p:{shifts:Shift[];members:Member[];me:Member;edit:boolean;onEdit:(d:Draft)=>void;closed?:ClosedDay}){const today=localDate();const rows=p.shifts.filter(s=>s.shift_date===today);return <><div className="hero"><p>TODAY'S CREW</p><h2>{jaDate(today,true)}</h2><span>今日の出勤メンバー</span></div>{p.closed&&<div className="closed-banner"><CalendarOff/><span>本日は休業日です（{p.closed.label}）</span></div>}{!p.closed&&<><ShiftList type="lunch" shifts={rows} members={p.members} edit={p.edit} onEdit={p.onEdit}/><ShiftList type="dinner" shifts={rows} members={p.members} edit={p.edit} onEdit={p.onEdit}/></>}<NextShift shifts={p.shifts} members={p.members} me={p.me}/></>}
function NextShift({shifts,members,me}:{shifts:Shift[];members:Member[];me:Member}){const today=localDate();const mine=shifts.filter(s=>s.member_id===me.id&&s.shift_date>today).sort((a,b)=>a.shift_date.localeCompare(b.shift_date)||a.start_time.localeCompare(b.start_time))[0];if(!mine)return <section className="next-shift empty-next"><div className="next-title"><Clock3/><div><small>NEXT SHIFT</small><h2>次の出勤は未登録です</h2></div></div></section>;const crew=shifts.filter(s=>s.shift_date===mine.shift_date).sort((a,b)=>a.start_time.localeCompare(b.start_time));return <section className="next-shift"><div className="next-title"><Clock3/><div><small>NEXT SHIFT</small><h2>次の出勤：{jaDate(mine.shift_date,true)}</h2><p>{mine.start_time.slice(0,5)} — {mine.end_time.slice(0,5)}</p></div></div><div className="next-crew"><small>その日にいる人</small>{crew.map(s=><div key={s.id}><time>{s.start_time.slice(0,5)}</time><span className="avatar">{shownName(members.find(m=>m.id===s.member_id)).slice(0,1)}</span><b>{shownName(members.find(m=>m.id===s.member_id))}</b><em>{s.end_time.slice(0,5)}まで</em></div>)}</div></section>}
function CalendarView({month,setMonth,shifts,closedDays,onDay}:{month:Date;setMonth:(d:Date)=>void;shifts:Shift[];closedDays:ClosedDay[];onDay:(d:string)=>void}){const y=month.getFullYear(),m=month.getMonth(),start=new Date(y,m,1-new Date(y,m,1).getDay());const days=Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d});return <section className="calendar-card"><div className="month-head"><button onClick={()=>setMonth(new Date(y,m-1,1))}><ChevronLeft/></button><h2>{y}年 {m+1}月</h2><button onClick={()=>setMonth(new Date(y,m+1,1))}><ChevronRight/></button></div><div className="week">{'日月火水木金土'.split('').map(x=><span key={x}>{x}</span>)}</div><div className="calendar">{days.map(d=>{const ds=localDate(d),closed=closedDays.find(c=>c.closed_date===ds),rows=shifts.filter(s=>s.shift_date===ds),l=rows.filter(s=>includesKind(s,'lunch')).length,n=rows.filter(s=>includesKind(s,'dinner')).length;return <button key={ds} className={`${d.getMonth()!==m?'outside':''} ${ds===localDate()?'today':''}`} onClick={()=>onDay(ds)}><b>{d.getDate()}</b>{closed?<span className="closed-dot">休業</span>:<>{l>0&&<span className="lunch-dot">昼 {l}</span>}{n>0&&<span className="dinner-dot">夜 {n}</span>}</>}</button>})}</div></section>}
function MembersView({members,shifts,onMember}:{members:Member[];shifts:Shift[];onMember:(id:string)=>void}){const month=localDate().slice(0,7);return <section className="member-grid"><div className="section-title"><p>CREW</p><h2>メンバー一覧</h2></div>{members.map(m=><button key={m.id} onClick={()=>onMember(m.id)}><span className="big-avatar">{shownName(m).slice(0,1)}</span><div><h3>{shownName(m)}</h3>{m.is_host&&<small>HOST</small>}<p>{shifts.filter(s=>s.member_id===m.id&&s.shift_date.startsWith(month)).length} shifts this month</p></div><ChevronRight/></button>)}</section>}
function SettingsView({me,members,history,edit,onToggle,onPayroll,onLogout,onRename}:{me:Member;members:Member[];history:History[];edit:boolean;onToggle:()=>void;onPayroll:()=>void;onLogout:()=>Promise<void>;onRename:(s:string)=>Promise<boolean>}){const [name,setName]=useState(shownName(me));useEffect(()=>setName(shownName(me)),[me.id,me.name,me.display_name]);return <section className="settings-page"><div className="profile"><span className="big-avatar">{shownName(me).slice(0,1)}</span><small>現在の表示名</small><h2>{shownName(me)}</h2><p>本人識別：{me.name}{me.is_host?' · ホスト':''}</p></div><div className="setting-card"><label>表示名</label><div className="inline"><input value={name} maxLength={24} onChange={e=>setName(e.target.value)}/><button onClick={()=>void onRename(name)}>保存</button></div><p>ゲームのユーザー名のように、いつでも変更できます。</p></div><button className="setting-row" onClick={onPayroll}><Calculator/><div><b>給料計算設定（テスト）</b><small>時給・深夜加算・交通費から概算</small></div></button><button className={`setting-row ${edit?'danger-row':''}`} onClick={onToggle}><Pencil/><div><b>{edit?'変更モードを終了':'変更モードに切り替え'}</b><small>全員分の追加・変更・削除</small></div></button><button className="setting-row logout-row" onClick={()=>void onLogout()}><LogOut/><div><b>ログアウト</b><small>この端末のログインを解除</small></div></button><details className="history"><summary><HistoryIcon/>最近の変更履歴</summary>{history.map(h=><div key={h.id}><b>{shownName(members.find(m=>m.id===h.actor_member_id))}</b> が {h.member_name||'メンバー'} のシフトを {h.action==='insert'?'追加':h.action==='update'?'変更':'削除'}<small>{new Date(h.created_at).toLocaleString('ja-JP')}</small></div>)}</details></section>}
function Modal({children,onClose,title}:{children:React.ReactNode;onClose:()=>void;title:string}){return <div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="modal-head"><h2>{title}</h2><button onClick={onClose}><X/></button></div>{children}</div></div>}
function DayModal({date,shifts,members,edit,closed,onClose,onEdit,onCloseDay,onOpenDay}:{date:string;shifts:Shift[];members:Member[];edit:boolean;closed?:ClosedDay;onClose:()=>void;onEdit:(d:Draft)=>void;onCloseDay:(label:string)=>void;onOpenDay:()=>void}){return <Modal title={jaDate(date,true)} onClose={onClose}>{closed?<div className="closed-banner"><CalendarOff/><span>休業日（{closed.label}）</span></div>:<><ShiftList type="lunch" shifts={shifts} members={members} edit={edit} onEdit={onEdit}/><ShiftList type="dinner" shifts={shifts} members={members} edit={edit} onEdit={onEdit}/></>}{edit&&<>{!closed&&<button className="primary wide" onClick={()=>onEdit({member_id:members[0]?.id||'',shift_date:date,start_time:'11:00',end_time:'15:00'})}><Plus/>この日に追加</button>}{closed?.kind==='temporary'?<button className="delete wide closed-action" onClick={onOpenDay}>臨時休業を解除</button>:!closed&&<button className="delete wide closed-action" onClick={()=>{const label=prompt('休業日の名前を入力してください','臨時休業');if(label?.trim())onCloseDay(label.trim())}}><CalendarOff/>臨時休業にする</button>}</>}</Modal>}
function MemberModal({member,shifts,onClose}:{member:Member;shifts:Shift[];onClose:()=>void}){const prefix=localDate().slice(0,7);return <Modal title={shownName(member)} onClose={onClose}><p className="real-name">本人識別：{member.name}</p><div className="member-shifts">{shifts.filter(s=>s.shift_date.startsWith(prefix)).map(s=><div key={s.id}><b>{jaDate(s.shift_date)}</b><span>{s.start_time.slice(0,5)} — {s.end_time.slice(0,5)}</span></div>)}</div></Modal>}
function ShiftModal({draft,members,onClose,onSave,onDelete}:{draft:Draft;members:Member[];onClose:()=>void;onSave:(d:Draft)=>void;onDelete:(id:string)=>void}){const [d,setD]=useState(draft);return <Modal title={d.id?'シフトを変更':'シフトを追加'} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(d)}} className="form"><label>メンバー<select value={d.member_id} onChange={e=>setD({...d,member_id:e.target.value})}>{members.map(m=><option key={m.id} value={m.id}>{shownName(m)}</option>)}</select></label><label>日付<input type="date" required value={d.shift_date} onChange={e=>setD({...d,shift_date:e.target.value})}/></label><div className="two"><label>入り<input type="time" required value={d.start_time.slice(0,5)} onChange={e=>setD({...d,start_time:e.target.value})}/></label><label>上がり<input type="time" required value={d.end_time.slice(0,5)} onChange={e=>setD({...d,end_time:e.target.value})}/></label></div><button className="primary wide" type="submit">保存する</button>{d.id&&<button className="delete wide" type="button" onClick={()=>onDelete(d.id!)}><Trash2/>削除する</button>}</form></Modal>}
function BulkModal({members,me,onClose,onSave}:{members:Member[];me:Member;onClose:()=>void;onSave:(r:Omit<Shift,'id'>[],replace:boolean)=>void}){const [member,setMember]=useState(me.id),[year,setYear]=useState(new Date().getFullYear()),[text,setText]=useState(''),[replace,setReplace]=useState(true);const rows=useMemo(()=>parseShiftBoard(text,year,member),[text,year,member]);return <Modal title="シフトボードから登録" onClose={onClose}><div className="form"><label>メンバー<select value={member} onChange={e=>setMember(e.target.value)}>{members.map(m=><option value={m.id} key={m.id}>{shownName(m)}</option>)}</select></label><label>対象年<input type="number" value={year} onChange={e=>setYear(+e.target.value)}/></label><label>貼り付け<textarea rows={8} value={text} onChange={e=>setText(e.target.value)} placeholder={'07/16（木）11:00 - 15:00\n07/17（金）19:30 - 23:30'}/></label><label className="check"><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>貼り付けた日付の既存シフトを置き換える</label><p className="preview"><Upload/> {rows.length}件を読み取りました</p><button disabled={!rows.length} className="primary wide" onClick={()=>onSave(rows,replace)}>登録する</button></div></Modal>}
