import {useEffect,useMemo,useState} from 'react';
import {CalendarDays,ChevronLeft,ChevronRight,Clock3,History as HistoryIcon,Home,Settings,Users,UtensilsCrossed,Moon,AlertTriangle,X,Plus,Pencil,Trash2,Upload} from 'lucide-react';
import {configured,History,includesKind,localDate,Member,parseShiftBoard,Shift,shownName,supabase} from './lib';

type Tab='today'|'calendar'|'members'|'settings';
type Draft={id?:string;member_id:string;shift_date:string;start_time:string;end_time:string};
const MEMBER_KEY='shiftcal-member-id'; const EDIT_KEY='shiftcal-edit-mode';
const jaDate=(s:string,detail=false)=>new Intl.DateTimeFormat('ja-JP',detail?{month:'long',day:'numeric',weekday:'short'}:{month:'numeric',day:'numeric',weekday:'short'}).format(new Date(`${s}T12:00:00`));

export default function App(){
 const [members,setMembers]=useState<Member[]>([]),[shifts,setShifts]=useState<Shift[]>([]),[history,setHistory]=useState<History[]>([]);
 const [meId,setMeId]=useState(localStorage.getItem(MEMBER_KEY)||''),[tab,setTab]=useState<Tab>('today'),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [edit,setEdit]=useState(sessionStorage.getItem(EDIT_KEY)==='1'),[month,setMonth]=useState(()=>new Date()),[selectedDate,setSelectedDate]=useState<string|null>(null),[selectedMember,setSelectedMember]=useState<string|null>(null),[draft,setDraft]=useState<Draft|null>(null),[bulk,setBulk]=useState(false);
 const me=members.find(m=>m.id===meId);
 const load=async()=>{const [m,s,h]=await Promise.all([supabase.from('members').select('id,name,display_name,is_host').order('name'),supabase.from('shifts').select('*').order('shift_date').order('start_time'),supabase.from('shift_history').select('*').order('created_at',{ascending:false}).limit(50)]);if(m.error||s.error){setError(m.error?.message||s.error?.message||'読込に失敗しました');return}setMembers(m.data||[]);setShifts(s.data||[]);setHistory(h.data||[])};
 useEffect(()=>{(async()=>{if(!configured){setError('Vercelの環境変数が設定されていません');setLoading(false);return}const {data}=await supabase.auth.getSession();if(!data.session){const r=await supabase.auth.signInAnonymously();if(r.error){setError('Supabaseで匿名サインインを有効にしてください');setLoading(false);return}}await load();setLoading(false)})();},[]);
 useEffect(()=>{if(loading)return;const channel=supabase.channel('shiftcal-live').on('postgres_changes',{event:'*',schema:'public',table:'shifts'},load).on('postgres_changes',{event:'*',schema:'public',table:'members'},load).subscribe();return()=>{void supabase.removeChannel(channel)}},[loading]);
 const choose=(id:string)=>{localStorage.setItem(MEMBER_KEY,id);setMeId(id)};
 const toggleEdit=()=>{const next=!edit;next?sessionStorage.setItem(EDIT_KEY,'1'):sessionStorage.removeItem(EDIT_KEY);setEdit(next)};
 const call=async(fn:string,args:Record<string,unknown>)=>{setError('');const r=await supabase.rpc(fn,args);if(r.error){setError(r.error.message);return false}await load();return true};
 const saveDraft=async(d:Draft)=>{if(!me)return;const args={p_actor_member_id:me.id,p_target_member_id:d.member_id,p_shift_date:d.shift_date,p_start_time:d.start_time,p_end_time:d.end_time};const ok=d.id?await call('update_shift',{p_shift_id:d.id,...args}):await call('create_shift',args);if(ok)setDraft(null)};
 const remove=async(id:string)=>{if(me&&confirm('このシフトを削除しますか？')&&await call('delete_shift',{p_shift_id:id,p_actor_member_id:me.id}))setDraft(null)};
 if(loading)return <div className="splash"><span className="logo">S</span><p>シフトを読み込んでいます</p></div>;
 if(!me)return <Identity members={members} error={error} onChoose={choose}/>;
 const title=tab==='today'?'今日':tab==='calendar'?'カレンダー':tab==='members'?'メンバー':'設定';
 return <div className="app"><header><div><small>{new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'long'}).format(new Date())}</small><h1>{title}</h1></div><button className={`mode ${edit?'active':''}`} onClick={toggleEdit}>{edit?'変更モード中':'閲覧モード'}</button></header>
  {error&&<div className="error">{error}<button onClick={()=>setError('')}><X size={16}/></button></div>}
  <main>
   {tab==='today'&&<Today shifts={shifts} members={members} edit={edit} onEdit={setDraft}/>}
   {tab==='calendar'&&<CalendarView month={month} setMonth={setMonth} shifts={shifts} onDay={setSelectedDate}/>}
   {tab==='members'&&<MembersView members={members} shifts={shifts} onMember={setSelectedMember}/>}
   {tab==='settings'&&<SettingsView me={me} members={members} history={history} edit={edit} onToggle={toggleEdit} onChoose={choose} onRename={async name=>{if(await call('set_display_name',{p_member_id:me.id,p_display_name:name}))return true;return false}}/>}
  </main>
  {edit&&<button className="fab" onClick={()=>setBulk(true)} aria-label="シフトを登録"><Plus/></button>}
  <nav>{([{id:'today',icon:Home,label:'今日'},{id:'calendar',icon:CalendarDays,label:'カレンダー'},{id:'members',icon:Users,label:'メンバー'},{id:'settings',icon:Settings,label:'設定'}] as const).map(i=><button className={tab===i.id?'active':''} onClick={()=>setTab(i.id)} key={i.id}><i.icon/><span>{i.label}</span></button>)}</nav>
  {selectedDate&&<DayModal date={selectedDate} shifts={shifts.filter(s=>s.shift_date===selectedDate)} members={members} edit={edit} onClose={()=>setSelectedDate(null)} onEdit={setDraft}/>}
  {selectedMember&&<MemberModal member={members.find(m=>m.id===selectedMember)!} shifts={shifts.filter(s=>s.member_id===selectedMember)} onClose={()=>setSelectedMember(null)}/>}
  {draft&&<ShiftModal draft={draft} members={members} onClose={()=>setDraft(null)} onSave={saveDraft} onDelete={remove}/>}
  {bulk&&<BulkModal members={members} me={me} onClose={()=>setBulk(false)} onSave={async(rows,replace)=>{const ok=await call('bulk_replace_shifts',{p_actor_member_id:me.id,p_target_member_id:rows[0].member_id,p_rows:rows.map(r=>({shift_date:r.shift_date,start_time:r.start_time,end_time:r.end_time})),p_replace:replace});if(ok)setBulk(false)}}/>}
 </div>
}

function Identity({members,error,onChoose}:{members:Member[];error:string;onChoose:(id:string)=>void}){return <div className="identity"><div className="identity-card"><span className="logo">S</span><p className="eyebrow">SHIFT CALENDAR</p><h1>あなたは誰ですか？</h1><p>最初の一度だけ選んでください。この端末に記憶します。</p>{error&&<div className="error">{error}</div>}<div className="people">{members.map((m,i)=><button key={m.id} onClick={()=>onChoose(m.id)}><span>{shownName(m).slice(0,1)}</span><b>{shownName(m)}</b><small>{i%2?'DINNER CREW':'TEAM MEMBER'}</small></button>)}</div></div></div>}
function ShiftList({type,shifts,members,edit,onEdit}:{type:'lunch'|'dinner';shifts:Shift[];members:Member[];edit:boolean;onEdit:(d:Draft)=>void}){const rows=shifts.filter(s=>includesKind(s,type)).sort((a,b)=>a.start_time.localeCompare(b.start_time));return <section className={`service ${type}`}><div className="service-head"><div>{type==='lunch'?<UtensilsCrossed/>:<Moon/>}<div><small>{type==='lunch'?'LUNCH':'DINNER'}</small><h2>{type==='lunch'?'ランチ':'ディナー'}</h2></div></div><div className={`count ${rows.length<=2?'warn':''}`}>{rows.length<=2&&<AlertTriangle/>}<strong>{rows.length}</strong><span>人</span></div></div><div className="shift-list">{rows.length?rows.map(s=><button key={s.id} onClick={()=>edit&&onEdit(s)}><time>{s.start_time.slice(0,5)}</time><span className="avatar">{shownName(members.find(m=>m.id===s.member_id)).slice(0,1)}</span><b>{shownName(members.find(m=>m.id===s.member_id))}</b><small>{s.end_time.slice(0,5)}まで</small>{edit&&<Pencil size={16}/>}</button>):<div className="empty">登録されたシフトはありません</div>}</div></section>}
function Today(p:{shifts:Shift[];members:Member[];edit:boolean;onEdit:(d:Draft)=>void}){const today=localDate();const rows=p.shifts.filter(s=>s.shift_date===today);return <><div className="hero"><p>TODAY'S CREW</p><h2>{jaDate(today,true)}</h2><span>今日の出勤メンバー</span></div><ShiftList type="lunch" shifts={rows} members={p.members} edit={p.edit} onEdit={p.onEdit}/><ShiftList type="dinner" shifts={rows} members={p.members} edit={p.edit} onEdit={p.onEdit}/></>}
function CalendarView({month,setMonth,shifts,onDay}:{month:Date;setMonth:(d:Date)=>void;shifts:Shift[];onDay:(d:string)=>void}){const y=month.getFullYear(),m=month.getMonth(),start=new Date(y,m,1-new Date(y,m,1).getDay());const days=Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d});return <section className="calendar-card"><div className="month-head"><button onClick={()=>setMonth(new Date(y,m-1,1))}><ChevronLeft/></button><h2>{y}年 {m+1}月</h2><button onClick={()=>setMonth(new Date(y,m+1,1))}><ChevronRight/></button></div><div className="week">{'日月火水木金土'.split('').map(x=><span key={x}>{x}</span>)}</div><div className="calendar">{days.map(d=>{const ds=localDate(d),rows=shifts.filter(s=>s.shift_date===ds),l=rows.filter(s=>includesKind(s,'lunch')).length,n=rows.filter(s=>includesKind(s,'dinner')).length;return <button key={ds} className={`${d.getMonth()!==m?'outside':''} ${ds===localDate()?'today':''}`} onClick={()=>onDay(ds)}><b>{d.getDate()}</b>{l>0&&<span className="lunch-dot">昼 {l}</span>}{n>0&&<span className="dinner-dot">夜 {n}</span>}</button>})}</div></section>}
function MembersView({members,shifts,onMember}:{members:Member[];shifts:Shift[];onMember:(id:string)=>void}){const month=localDate().slice(0,7);return <section className="member-grid"><div className="section-title"><p>CREW</p><h2>メンバー一覧</h2></div>{members.map(m=><button key={m.id} onClick={()=>onMember(m.id)}><span className="big-avatar">{shownName(m).slice(0,1)}</span><div><h3>{shownName(m)}</h3>{m.is_host&&<small>HOST</small>}<p>{shifts.filter(s=>s.member_id===m.id&&s.shift_date.startsWith(month)).length} shifts this month</p></div><ChevronRight/></button>)}</section>}
function SettingsView({me,members,history,edit,onToggle,onChoose,onRename}:{me:Member;members:Member[];history:History[];edit:boolean;onToggle:()=>void;onChoose:(id:string)=>void;onRename:(s:string)=>Promise<boolean>}){const [name,setName]=useState(shownName(me));const [open,setOpen]=useState(false);return <section className="settings-page"><div className="profile"><span className="big-avatar">{shownName(me).slice(0,1)}</span><small>現在の表示名</small><h2>{shownName(me)}</h2><p>本人識別：{me.name}{me.is_host?' · ホスト':''}</p></div><div className="setting-card"><label>表示名</label><div className="inline"><input value={name} maxLength={24} onChange={e=>setName(e.target.value)}/><button onClick={()=>void onRename(name)}>保存</button></div><p>ゲームのユーザー名のように、いつでも変更できます。</p></div><button className={`setting-row ${edit?'danger-row':''}`} onClick={onToggle}><Pencil/><div><b>{edit?'変更モードを終了':'変更モードに切り替え'}</b><small>全員分の追加・変更・削除</small></div></button><button className="setting-row" onClick={()=>setOpen(!open)}><Users/><div><b>本人選択を変更</b><small>別の人としてこの端末を使う</small></div></button>{open&&<div className="choice-list">{members.map(m=><button key={m.id} onClick={()=>onChoose(m.id)}>{shownName(m)} <small>({m.name})</small></button>)}</div>}<details className="history"><summary><HistoryIcon/>最近の変更履歴</summary>{history.map(h=><div key={h.id}><b>{shownName(members.find(m=>m.id===h.actor_member_id))}</b> が {h.member_name||'メンバー'} のシフトを {h.action==='insert'?'追加':h.action==='update'?'変更':'削除'}<small>{new Date(h.created_at).toLocaleString('ja-JP')}</small></div>)}</details></section>}
function Modal({children,onClose,title}:{children:React.ReactNode;onClose:()=>void;title:string}){return <div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="modal-head"><h2>{title}</h2><button onClick={onClose}><X/></button></div>{children}</div></div>}
function DayModal({date,shifts,members,edit,onClose,onEdit}:{date:string;shifts:Shift[];members:Member[];edit:boolean;onClose:()=>void;onEdit:(d:Draft)=>void}){return <Modal title={jaDate(date,true)} onClose={onClose}><ShiftList type="lunch" shifts={shifts} members={members} edit={edit} onEdit={onEdit}/><ShiftList type="dinner" shifts={shifts} members={members} edit={edit} onEdit={onEdit}/>{edit&&<button className="primary wide" onClick={()=>onEdit({member_id:members[0]?.id||'',shift_date:date,start_time:'11:00',end_time:'15:00'})}><Plus/>この日に追加</button>}</Modal>}
function MemberModal({member,shifts,onClose}:{member:Member;shifts:Shift[];onClose:()=>void}){const prefix=localDate().slice(0,7);return <Modal title={shownName(member)} onClose={onClose}><p className="real-name">本人識別：{member.name}</p><div className="member-shifts">{shifts.filter(s=>s.shift_date.startsWith(prefix)).map(s=><div key={s.id}><b>{jaDate(s.shift_date)}</b><span>{s.start_time.slice(0,5)} — {s.end_time.slice(0,5)}</span></div>)}</div></Modal>}
function ShiftModal({draft,members,onClose,onSave,onDelete}:{draft:Draft;members:Member[];onClose:()=>void;onSave:(d:Draft)=>void;onDelete:(id:string)=>void}){const [d,setD]=useState(draft);return <Modal title={d.id?'シフトを変更':'シフトを追加'} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(d)}} className="form"><label>メンバー<select value={d.member_id} onChange={e=>setD({...d,member_id:e.target.value})}>{members.map(m=><option key={m.id} value={m.id}>{shownName(m)}</option>)}</select></label><label>日付<input type="date" required value={d.shift_date} onChange={e=>setD({...d,shift_date:e.target.value})}/></label><div className="two"><label>入り<input type="time" required value={d.start_time.slice(0,5)} onChange={e=>setD({...d,start_time:e.target.value})}/></label><label>上がり<input type="time" required value={d.end_time.slice(0,5)} onChange={e=>setD({...d,end_time:e.target.value})}/></label></div><button className="primary wide" type="submit">保存する</button>{d.id&&<button className="delete wide" type="button" onClick={()=>onDelete(d.id!)}><Trash2/>削除する</button>}</form></Modal>}
function BulkModal({members,me,onClose,onSave}:{members:Member[];me:Member;onClose:()=>void;onSave:(r:Omit<Shift,'id'>[],replace:boolean)=>void}){const [member,setMember]=useState(me.id),[year,setYear]=useState(new Date().getFullYear()),[text,setText]=useState(''),[replace,setReplace]=useState(true);const rows=useMemo(()=>parseShiftBoard(text,year,member),[text,year,member]);return <Modal title="シフトボードから登録" onClose={onClose}><div className="form"><label>メンバー<select value={member} onChange={e=>setMember(e.target.value)}>{members.map(m=><option value={m.id} key={m.id}>{shownName(m)}</option>)}</select></label><label>対象年<input type="number" value={year} onChange={e=>setYear(+e.target.value)}/></label><label>貼り付け<textarea rows={8} value={text} onChange={e=>setText(e.target.value)} placeholder={'07/16（木）11:00 - 15:00\n07/17（金）19:30 - 23:30'}/></label><label className="check"><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>貼り付けた日付の既存シフトを置き換える</label><p className="preview"><Upload/> {rows.length}件を読み取りました</p><button disabled={!rows.length} className="primary wide" onClick={()=>onSave(rows,replace)}>登録する</button></div></Modal>}
